Permanently cache Central-Search results for Artifact-Identification
eclipse-m2e/m2e-core pull request #1204
Opened 2023-01-14 12:48 UTC by HannesWell

As suggested in #1196 this PR introduces a cache to avoid querying Maven-Central for the same artifact multiple times.

The cache stores the artifact's jar-file path and maps it to the artifact-keys returned by the Maven-Central search.

2023-01-14 19:32 UTC, mickaelistria commented
Files are mutable, for example if using some not-versioned file name which would suddenly use a newer version without the file path/name to change. So instead of storing a cache using File as key, I would suggest to store in cache the sha1->artifactId mapping, which is immutable and reusable. It also allows that several files with different path/names but the same sha1 (so same content) would only generate a single request to search.maven.org.

2023-01-14 19:39 UTC, mickaelistria requested changes

2023-01-14 19:39 UTC, mickaelistria commented on org.eclipse.m2e.core/src/org/eclipse/m2e/core/internal/MavenArtifactIdentifier.java
> +    static final Map<Path, Set<ArtifactKey>> IDS = loadCachedIds();
As mentioned, the key must be something immutable for safer caching.

2023-01-16 20:00 UTC, HannesWell commented
> Files are mutable, for example if using some not-versioned file name which would suddenly use a newer version without the file path/name to change. So instead of storing a cache using File as key, I would suggest to store in cache the sha1->artifactId mapping, which is immutable and reusable. It also allows that several files with different path/names but the same sha1 (so same content) would only generate a single request to search.maven.org.

That's all right. I wouldn't mind to check the same file at different location multiple times, but missing a changed file at the same location would be bad. Nevertheless caching by Path has the advantage that the file-content doesn't have to be read and therefore is probably significantly faster.
I think it would be possible to maintain another path-based cache that remembers the last-modified time of a file, is build at runtime and is queried first. With that an unchanged file is only hashed once. But because I'm still think that a successful look-up in Maven-Central is very unlikely (see https://github.com/eclipse-m2e/m2e-core/issues/1196#issuecomment-1381557334), I don't want to spent more time on this right now and leave that optimization to somebody that is interested (if there is anybody).

2023-01-16 20:07 UTC, mickaelistria approved these changes

2023-01-16 20:22 UTC, merged