Disable "Add ... dependency" quick fix due to bad user feedback
eclipse-m2e/m2e-core pull request #1329
Opened 2023-03-23 17:09 UTC by howlger

The m2e _"Add ... dependency"_ quick fix seems to have some issues that should be fixed before re-enabling it: see issue https://github.com/eclipse-m2e/m2e-core/issues/1328

Feedback from dissatisfied users:
- https://github.com/eclipse-m2e/m2e-core/issues/879#issuecomment-1470177817
- https://github.com/eclipse-m2e/m2e-core/issues/879#issuecomment-1478251753
- https://stackoverflow.com/q/75817981/6505250

2023-03-23 17:56 UTC, laeubi requested changes
Completely removing the feature is not a solution. Please add a m2e preference to enable / disable the feature via the UI.

2023-03-23 22:39 UTC, howlger commented
> Completely removing the feature is not a solution. Please add a m2e preference to enable / disable the feature via the UI.

I really like the idea of this feature. I don't want to remove it, nor do I want a preference to disable it (a preference wouldn't change that some users would be unsatisfied in the first place, and they would need to know that and where to disable it). In my view the problem is that there are currently false positive proposals. Even if almost all proposals are provided correctly, a few false positive proposals will result in a poor user experience. Performance might also be a blocker.

I opened issue https://github.com/eclipse-m2e/m2e-core/issues/1328 to fix and improve the feature which I guess will not be that easy. Maybe it would be better to provide a quick fix first on import statements that can't be resolved since the qualified name is known. I'm not a Maven power user, so I don't know what is the best and makes sense here. I was hoping to hear from @lukaseder and @kjaranso about what would be helpful to them, rather to hear what they don't like.

It would be great if the false positives will be fixed already in the next release. Otherwise, if more time is needed, I would appreciate if this feature would be disabled until the false positives are fixed.

2023-03-24 09:20 UTC, lukaseder commented
> I was hoping to hear from @lukaseder and @kjaranso about what would be helpful to them, rather to hear what they don't like.

Well, I would definitely love to be able to control what is displayed in quick fixes, just like in the Windows Explorer context menu. Every app/plugin/etc. has interesting ideas to contribute to a central menu, but users have very different tastes. In any case, this wouldn't be m2e specific, and perhaps a bit too broad, so I get what you're really looking for here.

What would be helpful to me:

1. I think the m2e suggestion should mostly be the lowest priority in a quick fix popup simply based on the fact that it is unlikely the most popular choice. Here's an example:

![image](https://user-images.githubusercontent.com/734593/227475965-d202e1ee-cf50-46fc-bf27-e1d163db9be5.png)

Sure, *maybe* I want to add a dependency, but very likely, I just want to create the type, too. There are some type names that are *very* likely from a dependency, like e.g. `Flux` from reactor. But many others aren't.

Also, how many times per day do I?

- Import stuff (all the time)
- Create types (often, but less often)
- Add dependencies (almost never, and if I do, I edit the pom.xml manually, because in my case, it's not trivial to decide where to add the dependency (e.g. in the project itself, or as a transitive dependency of the project, etc.))

2. Even if it was an occasionally good choice to add the dependency, perhaps the problem (when I first asked about this on Stack Overflow) was the overwhelming amount of options that distract me from what I *really* want to do. E.g. here's what IntelliJ does. It simply lists "Add Maven dependency..." (as a last option, even for `Flux`!):

![image](https://user-images.githubusercontent.com/734593/227476603-b5255649-d28d-48c2-8b7f-05c550279f80.png)

I don't know if this is possible in Eclipse (a quick fix that opens up a new wizard / popup, rather than executing the action directly), but for this particular purpose, I think it would be better.

2023-03-24 10:10 UTC, laeubi commented
A QuickFix can do literally anything, so it is just a matter of implementation :-)

Sadly there only a quite vague "priority" one can use to control the position of a quickfix and also no way like for autocomplete to have distinct categories (e.g Java, E4, SWT fixes).

2023-03-24 14:14 UTC, kjaranso commented
Well, as I had mentioned before, my biggest issue was the performance. It was literally taking it over 2 minutes to return after trying to get a quick fix, the entire while eclipse was unresponsive. That's not acceptable for me. I'm not sure if that can be solved by caching everything ahead of time or using some other search mechanism. The amount of time it took varied depending on which import it was looking for, too. I'm not sure what was causing some to take longer than others, though. The Builder lombok annotation was the one that took the longest for me.

I've been using the quick fix how it's been working for years, so I'm never expecting to have it find something I don't have included in my dependencies already. It does seem like it could be convenient to have it do that for me, but at least half the time the dependency won't be found by this new scheme since it won't be in my project already. Maybe if when you try to do the quick fix and it doesn't find something, it could ask if you want to search for a dependency in your project? That way the user can decide? I don't know if you could configure it so that is optional. You could have 3 modes:
1. Always look for imports from outside project dependencies
2. Never look for imports from outside project dependencies
3. Prompt to look for imports from project dependencies if no current project dependencies are found

Does that sound reasonable? I don't know how difficult it is to implement things with this plugin, so change it if that makes more sense to you.

That being said, if you're able to figure out the performance issue such that it is never slow giving a response, then maybe those options aren't needed.

2023-06-05 06:08 UTC, laeubi commented
I'm closing this in favor of 
- https://github.com/eclipse-m2e/m2e-core/pull/1409

where this feature can be disabled on demand.

2023-06-05 06:08 UTC, closed without merging