Fix "m2e plugin sometimes 'loses' resources" (#1511)
eclipse-m2e/m2e-core pull request #1629
Opened 2023-12-20 12:00 UTC by kohlschuetter

The Java Builder may delete files from the project output directory that need to be re-created by the m2e Maven Builder.

With commit 8e5cd4967eaca2698e8f7109461320e11a11d4d7 (a fix for #1275), any changes to the project output directory were ignored, leading to unexpected errors when running an application after modifying the project POM: resources were missing from the target classpath, leading all sorts of unexpected program behavior.

This change allows marking these changes as relevant, as long as the following conditions are met:

- The expected resource no longer exists (i.e., it was deleted by another builder, plugin or outside process)
- The modification applies to a resource in the classes or test-classes folder (i.e., outputLocation/testOutputLocation)

https://github.com/eclipse-m2e/m2e-core/issues/1511 https://github.com/eclipse-m2e/m2e-core/issues/1275

2023-12-20 12:33 UTC, kohlschuetter commented
CI failure: "Baseline problems found! Project version ..." can be fixed with https://github.com/eclipse-m2e/m2e-core/pull/1630

2023-12-20 13:13 UTC, laeubi commented on org.eclipse.m2e.core/src/org/eclipse/m2e/core/internal/builder/MavenBuilderImpl.java
> +          if(!resource.exists() && ((outputLocation != null && outputLocation.isPrefixOf(fullPath))
Please split this into smaller parts or maybe a method as such nested conditions are hard to read and understand, for example the frist and the second only differ in the location,

2023-12-20 13:40 UTC, laeubi commented
> CI failure: "Baseline problems found! Project version ..." can be fixed with #1630

Please include any version changes in your PR here.

2023-12-20 13:46 UTC, laeubi commented on org.eclipse.m2e.core/src/org/eclipse/m2e/core/internal/builder/MavenBuilderImpl.java
> +          if(!resource.exists() && isOutputOrTestOutput.test(fullPath)) {
```suggestion
          if(isOutputOrTestOutput.test(fullPath) && !resource.exists()) {
```
checking the prefix is probably a bit cheaper than checking all resources for existence.

2023-12-21 08:19 UTC, laeubi requested changes
The change looks good in general now and it seems a valid assumption that if the output folder is gone something must be happen.

But thinking more about it I think this is more fundamentally problem even though it is fixing things for resource plugin others might behave odd, one example is the maven-bundle-plugin or bnd-maven-plugins that might also place resources there.

Because of this, please apply the following changes:

1. `hasRelevantDelta` should return an enum that has the values: `DELTA` (the current 'true' return value), `FULL` (when detecting the new output folder is gone), `IRRELEVANT` (the current 'false' return value.
2. In `setupProjectBuildContext` a value of `FULL` should result in a `null` build delta passed so we make sure a full build is executed and not an incremental one.

2023-12-21 11:09 UTC, kohlschuetter commented
@laeubi I think your recently requested changes are beyond the scope of the bug, and therefore better suited for a separate refactoring. I also feel that it's more reasonable if you implement these changes the way you envision them, it will save us both unnecessary back and forth.

2023-12-22 11:42 UTC, merged