[cleanup] erefactor/EclipseJdt - Add/Remove '$NON-NLS$' tags
eclipse-m2e/m2e-core pull request #226
Opened 2021-06-08 17:35 UTC by cal101

Do you care for NLS-Tags and is it useful to clean up this way? It's a lot of changes.

EclipseJdt cleanup 'CleanupNlsTag' applied by erefactor.

For EclipseJdt see https://www.eclipse.org/eclipse/news/4.19/jdt.php
For erefactor see https://github.com/cal101/erefactor

2021-06-09 07:32 UTC, mickaelistria requested changes
I see a few UI strings that should be `//$NON-NLS-1$`

2021-06-09 07:32 UTC, mickaelistria commented on org.eclipse.m2e.core.ui.tests/META-INF/MANIFEST.MF
> +Bundle-Version: 1.18.2.qualifier
I don't think we need to bump to 1.18.2 since 1.18.1 version of this bundle was not released yet.

2021-06-09 07:32 UTC, mickaelistria commented on org.eclipse.m2e.binaryproject/src/org/eclipse/m2e/binaryproject/internal/AbstractBinaryProjectsImportJob.java
> +    super("Import binary projects"); //$NON-NLS-1$
This should typically be internationalized; hence `//$NON-NLS-1$` is erroneous here.

2021-06-09 07:32 UTC, mickaelistria commented on org.eclipse.m2e.binaryproject.ui/src/org/eclipse/m2e/binaryproject/ui/internal/BinaryProjectImportWizard.java
> +        new MavenDependenciesWizardPage(new ProjectImportConfiguration(), "Artifacts", "Select artifacts to import") { //$NON-NLS-1$ //$NON-NLS-2$
This should typically be internationalized; hence `//$NON-NLS-1$` is erroneous here.

2021-06-09 07:32 UTC, mickaelistria commented on org.eclipse.m2e.binaryproject/src/org/eclipse/m2e/binaryproject/internal/BinaryProjectPlugin.java
> +    String projectName = groupId + "_" + artifactId + "_" + version; //$NON-NLS-1$ //$NON-NLS-2$
using `'_'` instead of `"_"` is also anoter way to not bother with nls.

2021-06-09 07:32 UTC, mickaelistria commented on org.eclipse.m2e.core.ui/src/org/eclipse/m2e/core/ui/internal/wizards/MappingDiscoveryJob.java
> +    super("Discover lifecycle mappings"); //$NON-NLS-1$
This should typically be internationalized; hence `//$NON-NLS-1$` is erroneous here.

2021-06-09 07:32 UTC, mickaelistria commented on org.eclipse.m2e.core.ui/src/org/eclipse/m2e/core/ui/internal/wizards/MavenDiscoveryProposalWizard.java
> +      Job job = new WorkspaceJob("Apply Lifecycle Mapping Changes") { //$NON-NLS-1$
This should typically be internationalized; hence `//$NON-NLS-1$` is erroneous here.

2021-06-09 09:56 UTC, cal101 commented
To summarize:
- using the eclipse cleanups as is does not make much sense -> I agree. I remove the PR and ignore the cleanup
- the version bumper needs some fine tuning -> I will fix it

@mickaelistria There is a single cleanup that just removes wrong NLS tags. I think that may be useful and I prepare a separate PR for that.

2021-11-25 15:38 UTC, mickaelistria commented
@cal101 do you plan to address former comments? If not, please close the PR.

2021-12-02 21:47 UTC, closed without merging