Add support to lookup of extensions
eclipse-m2e/m2e-core pull request #729
Opened 2022-05-22 07:13 UTC by laeubi

This add first support of lookup extension components, currently only
project scoped extensions are supported but could be enhanced later to
support core extensions as well.

2022-05-22 07:45 UTC, laeubi commented
@kjsmita6 this should now be the "dynamic" variant of your change, do you think you can test this with your custom plugin as well? With tycho extension it looks like this:

![grafik](https://user-images.githubusercontent.com/1331477/169684476-a59ee271-09c1-485d-b389-5f9336af4a85.png)

2022-05-22 14:30 UTC, laeubi commented
@mickaelistria any concerns?

2022-05-22 17:03 UTC, kjsmita6 commented
@laeubi Looks good with my testing (checked out your fork). In my pom I have defined:
```xml
  <build>
        <plugins>
            <plugin>
                <groupId>com.tibco.ep</groupId>
                <artifactId>ep-maven-plugin</artifactId>
                <extensions>true</extensions>
            </plugin>
        </plugins>
    </build>
```

And shows up in the pom editor as:
![Screenshot (57)](https://user-images.githubusercontent.com/9405706/169706913-a2d910c8-5f8d-4c24-b0aa-2b0fc8fa1fa6.png)

2022-05-23 09:57 UTC, mickaelistria requested changes

2022-05-23 09:57 UTC, mickaelistria commented on org.eclipse.m2e.core.tests/src/org/eclipse/m2e/core/ExtensionsTest.java
> +package org.eclipse.m2e.core;
Please include legal header.

2022-05-23 09:59 UTC, mickaelistria commented
@laeubi I'd like to merge it ASAP (only concern is the missing copyright header on new file) as this improves an important part of m2e and really emphasizes the progress that are possible with recent changes.

2022-05-23 10:22 UTC, laeubi commented on org.eclipse.m2e.core.tests/src/org/eclipse/m2e/core/ExtensionsTest.java
> +package org.eclipse.m2e.core;
Done.

2022-05-23 10:23 UTC, laeubi commented
I have added the header now.

2022-05-23 10:44 UTC, merged

2022-05-23 10:44 UTC, mickaelistria commented
Thanks, that's a great patch!

2022-05-23 10:56 UTC, laeubi commented
> Thanks, that's a great patch!

Its just a first small step so don't be to enthusiastic :-)